# Generated by Django 4.2.8 on 2023-12-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Videos', '0002_alter_video_post_link_alter_video_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video_post',
            name='link',
            field=models.URLField(),
        ),
    ]
