# Generated by Django 4.2.8 on 2023-12-06 18:49

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('App_Videos', '0003_alter_video_post_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video_post',
            name='link',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
