# Generated by Django 4.2.8 on 2023-12-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Videos', '0004_alter_video_post_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='video_post',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
