# Generated by Django 4.2.8 on 2023-12-06 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Videos', '0005_video_post_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='video_post',
            name='category',
        ),
        migrations.AddField(
            model_name='video_post',
            name='cat',
            field=models.ForeignKey(blank=True, default=11, on_delete=django.db.models.deletion.CASCADE, to='App_Videos.category'),
            preserve_default=False,
        ),
    ]
