# Generated by Django 4.2.8 on 2023-12-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Videos', '0006_category_remove_video_post_category_video_post_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video_post',
            name='cat',
        ),
        migrations.AddField(
            model_name='video_post',
            name='category',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
