# Generated by Django 4.2.8 on 2023-12-07 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Videos', '0009_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='blog',
        ),
        migrations.AddField(
            model_name='comment',
            name='video',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='video_comment', to='App_Videos.video_post'),
            preserve_default=False,
        ),
    ]
